
<?php 
$page_title = 'Profile';
require_once('header.php');?>

										
										
<img src="/images/claudiabio.jpeg" style="float: left; margin: 20px 15px 15px 0;" height="200" width="200" /> 
	<h2 style="margin-top: 10px;">Biography</h2>
	<div id="bio-font-size">
		<p style="padding-right: 15px;">Claudia Myers was named one of <a href="http://independent-magazine.org/2015/05/10-to-watch-2015-claudia-myers/" target="_blank">"10 Filmmakers to Watch in 2015"</a> by Independent Magazine.  Most recently Claudia wrote and directed <a href="/work/above-the-shadows.php">Above the Shadows</a>, a supernatural action romance starring Olivia Thirlby, Alan Ritchson, Jim Gaffigan and Megan Fox. The film opened the 2019 Brooklyn Film Festival and won the Audience Award for Best Narrative Feature. Above the Shadows was released theatrically by Gravitas Ventures and is now widely available on demand. Prior to this, Claudia wrote, directed and produced the dramatic feature <a href="/work/fort-bliss.php">Fort Bliss</a> starring Michelle Monaghan and Ron Livingston. The film won several festival awards including Best Narrative Feature at the GI Film Festival, Honors for Outstanding Achievement in Filmmaking at the Newport Beach Film Festival, the Audience Award at the Champs Elysées Film Festival, and the Excellence in Acting Award at the San Diego Film Festival. Top critics for The Washington Post and Philadelphia Inquirer both cited Fort Bliss among the best films of 2014. Claudia also wrote and directed <a href="/work/kettle-of-fish.php">Kettle of Fish</a> starring Mathew Modine and Gina Gershon. The movie premiered at the Tribeca Film Festival and was released theatrically in 2007. She has directed two award-winning short films, including the Sundance short Buddy & Grace. As a screenwriter, Claudia has won several awards, was twice a finalist for the Sundance Screenwriters Lab, and is an alumna of the Hamptons Screenwriters Lab. Andy Tennant directed her script Wild Oats, starring Shirley MacLaine, Jessica Lange and Demi Moore, which was released in 2016.</p>

		<p style="padding-right: 15px;">Outside of narrative fiction, Claudia has worked with veterans and active duty soldiers to make several films about the military community. She produced and directed the documentary <a href="/work/long-road-back.php">“The Long Road Back,”</a> about soldiers who were severely injured in Iraq. The film won two Telly Awards, an Aurora Award, and was nominated for a regional Emmy. In 2010, Claudia produced and directed <a href="/work/women-at-war.php">“Women at War,”</a> a documentary about the evolution of women’s roles in the military. She also wrote and directed the interactive role-playing feature, <a href="/work/outside-wire.php">“Outside the Wire”</a> for use by the U.S. Army, which won a 20008 Codie Award and a Brandon Hall Excellence in Learning Award. The film pushes the boundaries of traditional narrative by melding fiction film, gaming, and educational training. Claudia subsequently wrote <a href="http://willinteractive.com/products/the-war-inside" target="_blank">“The War Inside”</a> another large-scale interactive, role-playing feature that deals with the psychological impact of war and aims to build resilience in soldiers. Claudia’s documentary, <a href="/work/women-on-wing.php">“Women on the Wing,”</a> about the legacy of Women Airforce Service Pilots who flew during WWII, won a Special Jury Award at Houston Worldfest.</p>

		<p style="padding-right: 15px;">Claudia studied literature at Yale then received her MFA in film at Columbia University. She is a professor in the Film & Media Arts division of American University’s School of Communication.</p>

	
	
	<!--
	
	<p style="padding-right: 15px; ">Claudia Myers was named by Independent Magazine as one of <a href="http://independent-magazine.org/2015/05/10-to-watch-2015-claudia-myers/" target="_blank">"10 Filmmakers to Watch in 2015."</a> Most recently, she wrote, directed and produced the feature <a href="/work/fort-bliss.php">"Fort Bliss"</a> starring Michelle Monaghan, about a female Army medic and single mother who returns from deployment and must rebuild her relationship with her young son. Released in 2014, the film won several festival awards including Best Narrative Feature at the GI Film Festival, Honors for Outstanding Achievement in Filmmaking at the Newport Beach Film Festival, the Audience Award at the Champs Elysées Film Festival, and the Excellence in Acting Award at the San Diego Film Festival. Previously, Claudia directed <a href="/work/kettle-of-fish.php">"Kettle of Fish"</a> starring Matthew Modine and Gina Gershon. The movie premiered at the Tribeca Film Festival and was cited as one of the standout films in David Carr's festival overview for The New York Times. It was released theatrically in 2007 then acquired by Showtime. Claudia's script Wild Oats, directed by Andy Tennant and starring Shirley MacLaine, Jessica Lange and Demi Moore will be released by the Weinstein company in 2015. Claudia also produced the independent comedy <a href="/work/below-beltway.php">"Below the Beltway"</a> starring Tate Donovan. The film won the Audience Award at the 2010 Newport Beach film festival and was acquired by Showtime. As a screenwriter, Claudia has won several awards, was twice a finalist for the Sundance Screenwriters Lab, and is a recent alum of the Hamptons Screenwriters Lab. She has also directed two award-winning short films, including the Sundance short <a href="/work/buddy-grace.php">"Buddy &amp; Grace."</a></p>

	<p style="padding-right: 15px;">Outside of narrative fiction, Claudia has worked with veterans and active duty soldiers to make several films about the military community. She produced and directed the documentary <a href="/work/long-road-back.php">"The Long Road Back,"</a> about soldiers who were severely injured in Iraq. The film won two Telly Awards, an Aurora Award, and was nominated for a Regional Emmy. In 2010, Claudia produced and directed <a href="/work/women-at-war.php">"Women At War,"</a> a documentary about the evolution of women's roles in the military. She also wrote and directed the interactive role-playing feature, <a href="/work/outside-wire.php">"Outside the Wire"</a> for use by the U.S. Army, which won a 2008 Codie Award and a Brandon Hall Excellence in Learning Award. The film pushes the boundaries of traditional narrative by melding fiction film, gaming, and educational training. Claudia subsequently wrote <a href="http://willinteractive.com/products/the-war-inside" target="_blank">"The War Inside"</a> another large-scale interactive, role-playing film that deals with the psychological impact of war and aims to build resilience in soldiers. Claudia's documentary <a href="/work/women-on-wing.php">"Women on the Wing,"</a> about the legacy of Women Airforce Service Pilots who flew during WWII, won a Special Jury Award at Houston Worldfest.</p>

	<p style="padding-right: 15px;">Claudia is a professor in the Film &amp; Media Arts division of <a href="http://www.american.edu/soc/" target="_blank">American University's School of Communication</a>. </p>
	
	-->

</div>

<?php require_once('footer.php');?>